# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-16 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telnumverifyrecord',
            name='status',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='true_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='zzs'),
        ),
    ]
